#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite_DKTKViecLam.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TKDKVIECLAM")]
	public partial class QL_TKVLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAIDANG(BAIDANG instance);
    partial void UpdateBAIDANG(BAIDANG instance);
    partial void DeleteBAIDANG(BAIDANG instance);
    partial void InsertTK_Admin(TK_Admin instance);
    partial void UpdateTK_Admin(TK_Admin instance);
    partial void DeleteTK_Admin(TK_Admin instance);
    partial void InsertDOANHNGHIEP(DOANHNGHIEP instance);
    partial void UpdateDOANHNGHIEP(DOANHNGHIEP instance);
    partial void DeleteDOANHNGHIEP(DOANHNGHIEP instance);
    partial void InsertDUYET(DUYET instance);
    partial void UpdateDUYET(DUYET instance);
    partial void DeleteDUYET(DUYET instance);
    partial void InsertHOSOUNGTUYEN(HOSOUNGTUYEN instance);
    partial void UpdateHOSOUNGTUYEN(HOSOUNGTUYEN instance);
    partial void DeleteHOSOUNGTUYEN(HOSOUNGTUYEN instance);
    partial void InsertLOAICONGVIEC(LOAICONGVIEC instance);
    partial void UpdateLOAICONGVIEC(LOAICONGVIEC instance);
    partial void DeleteLOAICONGVIEC(LOAICONGVIEC instance);
    partial void InsertNGUOIUNGTUYEN(NGUOIUNGTUYEN instance);
    partial void UpdateNGUOIUNGTUYEN(NGUOIUNGTUYEN instance);
    partial void DeleteNGUOIUNGTUYEN(NGUOIUNGTUYEN instance);
    #endregion
		
		public QL_TKVLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MayTin"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TKVLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TKVLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TKVLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_TKVLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAIDANG> BAIDANGs
		{
			get
			{
				return this.GetTable<BAIDANG>();
			}
		}
		
		public System.Data.Linq.Table<TK_Admin> TK_Admins
		{
			get
			{
				return this.GetTable<TK_Admin>();
			}
		}
		
		public System.Data.Linq.Table<DOANHNGHIEP> DOANHNGHIEPs
		{
			get
			{
				return this.GetTable<DOANHNGHIEP>();
			}
		}
		
		public System.Data.Linq.Table<DUYET> DUYETs
		{
			get
			{
				return this.GetTable<DUYET>();
			}
		}
		
		public System.Data.Linq.Table<HOSOUNGTUYEN> HOSOUNGTUYENs
		{
			get
			{
				return this.GetTable<HOSOUNGTUYEN>();
			}
		}
		
		public System.Data.Linq.Table<LOAICONGVIEC> LOAICONGVIECs
		{
			get
			{
				return this.GetTable<LOAICONGVIEC>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIUNGTUYEN> NGUOIUNGTUYENs
		{
			get
			{
				return this.GetTable<NGUOIUNGTUYEN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Duyet_Insert")]
		public int sp_Duyet_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaBD", DbType="NChar(20)")] string maBD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaAD", DbType="NChar(20)")] string maAD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maBD, maAD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.XuatBDtheoDn")]
		public ISingleResult<XuatBDtheoDnResult> XuatBDtheoDn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tendn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tendn);
			return ((ISingleResult<XuatBDtheoDnResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAIDANG")]
	public partial class BAIDANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBD;
		
		private string _TenBD;
		
		private string _MaDN;
		
		private string _Maloai;
		
		private string _Mota;
		
		private string _Phucloi;
		
		private string _Vitri;
		
		private string _Kinhnghiem;
		
		private string _Dotuoilamviec;
		
		private string _Mucluong;
		
		private System.Nullable<System.DateTime> _Ngaydangbai;
		
		private string _Yeucau;
		
		private string _Trangthai_BD;
		
		private EntitySet<DUYET> _DUYETs;
		
		private EntitySet<HOSOUNGTUYEN> _HOSOUNGTUYENs;
		
		private EntityRef<DOANHNGHIEP> _DOANHNGHIEP;
		
		private EntityRef<LOAICONGVIEC> _LOAICONGVIEC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBDChanging(string value);
    partial void OnMaBDChanged();
    partial void OnTenBDChanging(string value);
    partial void OnTenBDChanged();
    partial void OnMaDNChanging(string value);
    partial void OnMaDNChanged();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnPhucloiChanging(string value);
    partial void OnPhucloiChanged();
    partial void OnVitriChanging(string value);
    partial void OnVitriChanged();
    partial void OnKinhnghiemChanging(string value);
    partial void OnKinhnghiemChanged();
    partial void OnDotuoilamviecChanging(string value);
    partial void OnDotuoilamviecChanged();
    partial void OnMucluongChanging(string value);
    partial void OnMucluongChanged();
    partial void OnNgaydangbaiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangbaiChanged();
    partial void OnYeucauChanging(string value);
    partial void OnYeucauChanged();
    partial void OnTrangthai_BDChanging(string value);
    partial void OnTrangthai_BDChanged();
    #endregion
		
		public BAIDANG()
		{
			this._DUYETs = new EntitySet<DUYET>(new Action<DUYET>(this.attach_DUYETs), new Action<DUYET>(this.detach_DUYETs));
			this._HOSOUNGTUYENs = new EntitySet<HOSOUNGTUYEN>(new Action<HOSOUNGTUYEN>(this.attach_HOSOUNGTUYENs), new Action<HOSOUNGTUYEN>(this.detach_HOSOUNGTUYENs));
			this._DOANHNGHIEP = default(EntityRef<DOANHNGHIEP>);
			this._LOAICONGVIEC = default(EntityRef<LOAICONGVIEC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBD", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBD
		{
			get
			{
				return this._MaBD;
			}
			set
			{
				if ((this._MaBD != value))
				{
					this.OnMaBDChanging(value);
					this.SendPropertyChanging();
					this._MaBD = value;
					this.SendPropertyChanged("MaBD");
					this.OnMaBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBD", DbType="NVarChar(100)")]
		public string TenBD
		{
			get
			{
				return this._TenBD;
			}
			set
			{
				if ((this._TenBD != value))
				{
					this.OnTenBDChanging(value);
					this.SendPropertyChanging();
					this._TenBD = value;
					this.SendPropertyChanged("TenBD");
					this.OnTenBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="NChar(20)")]
		public string MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					if (this._DOANHNGHIEP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NChar(20)")]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					if (this._LOAICONGVIEC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(1000)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phucloi", DbType="NVarChar(1000)")]
		public string Phucloi
		{
			get
			{
				return this._Phucloi;
			}
			set
			{
				if ((this._Phucloi != value))
				{
					this.OnPhucloiChanging(value);
					this.SendPropertyChanging();
					this._Phucloi = value;
					this.SendPropertyChanged("Phucloi");
					this.OnPhucloiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri", DbType="NVarChar(1000)")]
		public string Vitri
		{
			get
			{
				return this._Vitri;
			}
			set
			{
				if ((this._Vitri != value))
				{
					this.OnVitriChanging(value);
					this.SendPropertyChanging();
					this._Vitri = value;
					this.SendPropertyChanged("Vitri");
					this.OnVitriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kinhnghiem", DbType="NVarChar(1000)")]
		public string Kinhnghiem
		{
			get
			{
				return this._Kinhnghiem;
			}
			set
			{
				if ((this._Kinhnghiem != value))
				{
					this.OnKinhnghiemChanging(value);
					this.SendPropertyChanging();
					this._Kinhnghiem = value;
					this.SendPropertyChanged("Kinhnghiem");
					this.OnKinhnghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dotuoilamviec", DbType="NVarChar(100)")]
		public string Dotuoilamviec
		{
			get
			{
				return this._Dotuoilamviec;
			}
			set
			{
				if ((this._Dotuoilamviec != value))
				{
					this.OnDotuoilamviecChanging(value);
					this.SendPropertyChanging();
					this._Dotuoilamviec = value;
					this.SendPropertyChanged("Dotuoilamviec");
					this.OnDotuoilamviecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mucluong", DbType="NVarChar(1000)")]
		public string Mucluong
		{
			get
			{
				return this._Mucluong;
			}
			set
			{
				if ((this._Mucluong != value))
				{
					this.OnMucluongChanging(value);
					this.SendPropertyChanging();
					this._Mucluong = value;
					this.SendPropertyChanged("Mucluong");
					this.OnMucluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangbai", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydangbai
		{
			get
			{
				return this._Ngaydangbai;
			}
			set
			{
				if ((this._Ngaydangbai != value))
				{
					this.OnNgaydangbaiChanging(value);
					this.SendPropertyChanging();
					this._Ngaydangbai = value;
					this.SendPropertyChanged("Ngaydangbai");
					this.OnNgaydangbaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yeucau", DbType="NVarChar(1000)")]
		public string Yeucau
		{
			get
			{
				return this._Yeucau;
			}
			set
			{
				if ((this._Yeucau != value))
				{
					this.OnYeucauChanging(value);
					this.SendPropertyChanging();
					this._Yeucau = value;
					this.SendPropertyChanged("Yeucau");
					this.OnYeucauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai_BD", DbType="NVarChar(50)")]
		public string Trangthai_BD
		{
			get
			{
				return this._Trangthai_BD;
			}
			set
			{
				if ((this._Trangthai_BD != value))
				{
					this.OnTrangthai_BDChanging(value);
					this.SendPropertyChanging();
					this._Trangthai_BD = value;
					this.SendPropertyChanged("Trangthai_BD");
					this.OnTrangthai_BDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAIDANG_DUYET", Storage="_DUYETs", ThisKey="MaBD", OtherKey="MaBD")]
		public EntitySet<DUYET> DUYETs
		{
			get
			{
				return this._DUYETs;
			}
			set
			{
				this._DUYETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAIDANG_HOSOUNGTUYEN", Storage="_HOSOUNGTUYENs", ThisKey="MaBD", OtherKey="MaBD")]
		public EntitySet<HOSOUNGTUYEN> HOSOUNGTUYENs
		{
			get
			{
				return this._HOSOUNGTUYENs;
			}
			set
			{
				this._HOSOUNGTUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANHNGHIEP_BAIDANG", Storage="_DOANHNGHIEP", ThisKey="MaDN", OtherKey="MaDN", IsForeignKey=true)]
		public DOANHNGHIEP DOANHNGHIEP
		{
			get
			{
				return this._DOANHNGHIEP.Entity;
			}
			set
			{
				DOANHNGHIEP previousValue = this._DOANHNGHIEP.Entity;
				if (((previousValue != value) 
							|| (this._DOANHNGHIEP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOANHNGHIEP.Entity = null;
						previousValue.BAIDANGs.Remove(this);
					}
					this._DOANHNGHIEP.Entity = value;
					if ((value != null))
					{
						value.BAIDANGs.Add(this);
						this._MaDN = value.MaDN;
					}
					else
					{
						this._MaDN = default(string);
					}
					this.SendPropertyChanged("DOANHNGHIEP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICONGVIEC_BAIDANG", Storage="_LOAICONGVIEC", ThisKey="Maloai", OtherKey="Maloai", IsForeignKey=true)]
		public LOAICONGVIEC LOAICONGVIEC
		{
			get
			{
				return this._LOAICONGVIEC.Entity;
			}
			set
			{
				LOAICONGVIEC previousValue = this._LOAICONGVIEC.Entity;
				if (((previousValue != value) 
							|| (this._LOAICONGVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAICONGVIEC.Entity = null;
						previousValue.BAIDANGs.Remove(this);
					}
					this._LOAICONGVIEC.Entity = value;
					if ((value != null))
					{
						value.BAIDANGs.Add(this);
						this._Maloai = value.Maloai;
					}
					else
					{
						this._Maloai = default(string);
					}
					this.SendPropertyChanged("LOAICONGVIEC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DUYETs(DUYET entity)
		{
			this.SendPropertyChanging();
			entity.BAIDANG = this;
		}
		
		private void detach_DUYETs(DUYET entity)
		{
			this.SendPropertyChanging();
			entity.BAIDANG = null;
		}
		
		private void attach_HOSOUNGTUYENs(HOSOUNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.BAIDANG = this;
		}
		
		private void detach_HOSOUNGTUYENs(HOSOUNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.BAIDANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TK_Admin")]
	public partial class TK_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaAD;
		
		private string _Hoten;
		
		private string _Diachi;
		
		private string _SDT;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Gioitinh;
		
		private string _Password_AD;
		
		private EntitySet<DUYET> _DUYETs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaADChanging(string value);
    partial void OnMaADChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnPassword_ADChanging(string value);
    partial void OnPassword_ADChanged();
    #endregion
		
		public TK_Admin()
		{
			this._DUYETs = new EntitySet<DUYET>(new Action<DUYET>(this.attach_DUYETs), new Action<DUYET>(this.detach_DUYETs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAD", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaAD
		{
			get
			{
				return this._MaAD;
			}
			set
			{
				if ((this._MaAD != value))
				{
					this.OnMaADChanging(value);
					this.SendPropertyChanging();
					this._MaAD = value;
					this.SendPropertyChanged("MaAD");
					this.OnMaADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(10)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_AD", DbType="NVarChar(100)")]
		public string Password_AD
		{
			get
			{
				return this._Password_AD;
			}
			set
			{
				if ((this._Password_AD != value))
				{
					this.OnPassword_ADChanging(value);
					this.SendPropertyChanging();
					this._Password_AD = value;
					this.SendPropertyChanged("Password_AD");
					this.OnPassword_ADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TK_Admin_DUYET", Storage="_DUYETs", ThisKey="MaAD", OtherKey="MaAD")]
		public EntitySet<DUYET> DUYETs
		{
			get
			{
				return this._DUYETs;
			}
			set
			{
				this._DUYETs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DUYETs(DUYET entity)
		{
			this.SendPropertyChanging();
			entity.TK_Admin = this;
		}
		
		private void detach_DUYETs(DUYET entity)
		{
			this.SendPropertyChanging();
			entity.TK_Admin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOANHNGHIEP")]
	public partial class DOANHNGHIEP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDN;
		
		private string _TenDN;
		
		private string _Diachi;
		
		private string _Email;
		
		private string _SDT;
		
		private string _Namthanhlap;
		
		private string _Tinhthanh;
		
		private string _Password_DN;
		
		private string _Trangthai_DN;
		
		private EntitySet<BAIDANG> _BAIDANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDNChanging(string value);
    partial void OnMaDNChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNamthanhlapChanging(string value);
    partial void OnNamthanhlapChanged();
    partial void OnTinhthanhChanging(string value);
    partial void OnTinhthanhChanged();
    partial void OnPassword_DNChanging(string value);
    partial void OnPassword_DNChanged();
    partial void OnTrangthai_DNChanging(string value);
    partial void OnTrangthai_DNChanged();
    #endregion
		
		public DOANHNGHIEP()
		{
			this._BAIDANGs = new EntitySet<BAIDANG>(new Action<BAIDANG>(this.attach_BAIDANGs), new Action<BAIDANG>(this.detach_BAIDANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="NVarChar(100)")]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namthanhlap", DbType="Char(4)")]
		public string Namthanhlap
		{
			get
			{
				return this._Namthanhlap;
			}
			set
			{
				if ((this._Namthanhlap != value))
				{
					this.OnNamthanhlapChanging(value);
					this.SendPropertyChanging();
					this._Namthanhlap = value;
					this.SendPropertyChanged("Namthanhlap");
					this.OnNamthanhlapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhthanh", DbType="NVarChar(50)")]
		public string Tinhthanh
		{
			get
			{
				return this._Tinhthanh;
			}
			set
			{
				if ((this._Tinhthanh != value))
				{
					this.OnTinhthanhChanging(value);
					this.SendPropertyChanging();
					this._Tinhthanh = value;
					this.SendPropertyChanged("Tinhthanh");
					this.OnTinhthanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_DN", DbType="NVarChar(100)")]
		public string Password_DN
		{
			get
			{
				return this._Password_DN;
			}
			set
			{
				if ((this._Password_DN != value))
				{
					this.OnPassword_DNChanging(value);
					this.SendPropertyChanging();
					this._Password_DN = value;
					this.SendPropertyChanged("Password_DN");
					this.OnPassword_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai_DN", DbType="NVarChar(50)")]
		public string Trangthai_DN
		{
			get
			{
				return this._Trangthai_DN;
			}
			set
			{
				if ((this._Trangthai_DN != value))
				{
					this.OnTrangthai_DNChanging(value);
					this.SendPropertyChanging();
					this._Trangthai_DN = value;
					this.SendPropertyChanged("Trangthai_DN");
					this.OnTrangthai_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOANHNGHIEP_BAIDANG", Storage="_BAIDANGs", ThisKey="MaDN", OtherKey="MaDN")]
		public EntitySet<BAIDANG> BAIDANGs
		{
			get
			{
				return this._BAIDANGs;
			}
			set
			{
				this._BAIDANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAIDANGs(BAIDANG entity)
		{
			this.SendPropertyChanging();
			entity.DOANHNGHIEP = this;
		}
		
		private void detach_BAIDANGs(BAIDANG entity)
		{
			this.SendPropertyChanging();
			entity.DOANHNGHIEP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DUYET")]
	public partial class DUYET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBD;
		
		private string _MaAD;
		
		private System.Nullable<System.DateTime> _Ngayduyet;
		
		private EntityRef<BAIDANG> _BAIDANG;
		
		private EntityRef<TK_Admin> _TK_Admin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBDChanging(string value);
    partial void OnMaBDChanged();
    partial void OnMaADChanging(string value);
    partial void OnMaADChanged();
    partial void OnNgayduyetChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayduyetChanged();
    #endregion
		
		public DUYET()
		{
			this._BAIDANG = default(EntityRef<BAIDANG>);
			this._TK_Admin = default(EntityRef<TK_Admin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBD", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBD
		{
			get
			{
				return this._MaBD;
			}
			set
			{
				if ((this._MaBD != value))
				{
					if (this._BAIDANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBDChanging(value);
					this.SendPropertyChanging();
					this._MaBD = value;
					this.SendPropertyChanged("MaBD");
					this.OnMaBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAD", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaAD
		{
			get
			{
				return this._MaAD;
			}
			set
			{
				if ((this._MaAD != value))
				{
					if (this._TK_Admin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaADChanging(value);
					this.SendPropertyChanging();
					this._MaAD = value;
					this.SendPropertyChanged("MaAD");
					this.OnMaADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayduyet", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayduyet
		{
			get
			{
				return this._Ngayduyet;
			}
			set
			{
				if ((this._Ngayduyet != value))
				{
					this.OnNgayduyetChanging(value);
					this.SendPropertyChanging();
					this._Ngayduyet = value;
					this.SendPropertyChanged("Ngayduyet");
					this.OnNgayduyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAIDANG_DUYET", Storage="_BAIDANG", ThisKey="MaBD", OtherKey="MaBD", IsForeignKey=true)]
		public BAIDANG BAIDANG
		{
			get
			{
				return this._BAIDANG.Entity;
			}
			set
			{
				BAIDANG previousValue = this._BAIDANG.Entity;
				if (((previousValue != value) 
							|| (this._BAIDANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BAIDANG.Entity = null;
						previousValue.DUYETs.Remove(this);
					}
					this._BAIDANG.Entity = value;
					if ((value != null))
					{
						value.DUYETs.Add(this);
						this._MaBD = value.MaBD;
					}
					else
					{
						this._MaBD = default(string);
					}
					this.SendPropertyChanged("BAIDANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TK_Admin_DUYET", Storage="_TK_Admin", ThisKey="MaAD", OtherKey="MaAD", IsForeignKey=true)]
		public TK_Admin TK_Admin
		{
			get
			{
				return this._TK_Admin.Entity;
			}
			set
			{
				TK_Admin previousValue = this._TK_Admin.Entity;
				if (((previousValue != value) 
							|| (this._TK_Admin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TK_Admin.Entity = null;
						previousValue.DUYETs.Remove(this);
					}
					this._TK_Admin.Entity = value;
					if ((value != null))
					{
						value.DUYETs.Add(this);
						this._MaAD = value.MaAD;
					}
					else
					{
						this._MaAD = default(string);
					}
					this.SendPropertyChanged("TK_Admin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOSOUNGTUYEN")]
	public partial class HOSOUNGTUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHS;
		
		private string _MaNUT;
		
		private string _MaBD;
		
		private string _CV_HSUT;
		
		private System.Nullable<System.DateTime> _NgaydangkyUT;
		
		private EntityRef<BAIDANG> _BAIDANG;
		
		private EntityRef<NGUOIUNGTUYEN> _NGUOIUNGTUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHSChanging(string value);
    partial void OnMAHSChanged();
    partial void OnMaNUTChanging(string value);
    partial void OnMaNUTChanged();
    partial void OnMaBDChanging(string value);
    partial void OnMaBDChanged();
    partial void OnCV_HSUTChanging(string value);
    partial void OnCV_HSUTChanged();
    partial void OnNgaydangkyUTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangkyUTChanged();
    #endregion
		
		public HOSOUNGTUYEN()
		{
			this._BAIDANG = default(EntityRef<BAIDANG>);
			this._NGUOIUNGTUYEN = default(EntityRef<NGUOIUNGTUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					this.OnMAHSChanging(value);
					this.SendPropertyChanging();
					this._MAHS = value;
					this.SendPropertyChanged("MAHS");
					this.OnMAHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNUT", DbType="NChar(20)")]
		public string MaNUT
		{
			get
			{
				return this._MaNUT;
			}
			set
			{
				if ((this._MaNUT != value))
				{
					if (this._NGUOIUNGTUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNUTChanging(value);
					this.SendPropertyChanging();
					this._MaNUT = value;
					this.SendPropertyChanged("MaNUT");
					this.OnMaNUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBD", DbType="NChar(20)")]
		public string MaBD
		{
			get
			{
				return this._MaBD;
			}
			set
			{
				if ((this._MaBD != value))
				{
					if (this._BAIDANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBDChanging(value);
					this.SendPropertyChanging();
					this._MaBD = value;
					this.SendPropertyChanged("MaBD");
					this.OnMaBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CV_HSUT", DbType="NVarChar(500)")]
		public string CV_HSUT
		{
			get
			{
				return this._CV_HSUT;
			}
			set
			{
				if ((this._CV_HSUT != value))
				{
					this.OnCV_HSUTChanging(value);
					this.SendPropertyChanging();
					this._CV_HSUT = value;
					this.SendPropertyChanged("CV_HSUT");
					this.OnCV_HSUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaydangkyUT", DbType="Date")]
		public System.Nullable<System.DateTime> NgaydangkyUT
		{
			get
			{
				return this._NgaydangkyUT;
			}
			set
			{
				if ((this._NgaydangkyUT != value))
				{
					this.OnNgaydangkyUTChanging(value);
					this.SendPropertyChanging();
					this._NgaydangkyUT = value;
					this.SendPropertyChanged("NgaydangkyUT");
					this.OnNgaydangkyUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAIDANG_HOSOUNGTUYEN", Storage="_BAIDANG", ThisKey="MaBD", OtherKey="MaBD", IsForeignKey=true)]
		public BAIDANG BAIDANG
		{
			get
			{
				return this._BAIDANG.Entity;
			}
			set
			{
				BAIDANG previousValue = this._BAIDANG.Entity;
				if (((previousValue != value) 
							|| (this._BAIDANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BAIDANG.Entity = null;
						previousValue.HOSOUNGTUYENs.Remove(this);
					}
					this._BAIDANG.Entity = value;
					if ((value != null))
					{
						value.HOSOUNGTUYENs.Add(this);
						this._MaBD = value.MaBD;
					}
					else
					{
						this._MaBD = default(string);
					}
					this.SendPropertyChanged("BAIDANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIUNGTUYEN_HOSOUNGTUYEN", Storage="_NGUOIUNGTUYEN", ThisKey="MaNUT", OtherKey="MaNUT", IsForeignKey=true)]
		public NGUOIUNGTUYEN NGUOIUNGTUYEN
		{
			get
			{
				return this._NGUOIUNGTUYEN.Entity;
			}
			set
			{
				NGUOIUNGTUYEN previousValue = this._NGUOIUNGTUYEN.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIUNGTUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIUNGTUYEN.Entity = null;
						previousValue.HOSOUNGTUYENs.Remove(this);
					}
					this._NGUOIUNGTUYEN.Entity = value;
					if ((value != null))
					{
						value.HOSOUNGTUYENs.Add(this);
						this._MaNUT = value.MaNUT;
					}
					else
					{
						this._MaNUT = default(string);
					}
					this.SendPropertyChanged("NGUOIUNGTUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAICONGVIEC")]
	public partial class LOAICONGVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maloai;
		
		private string _Tenloai;
		
		private string _Anh_Cviec;
		
		private EntitySet<BAIDANG> _BAIDANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    partial void OnTenloaiChanging(string value);
    partial void OnTenloaiChanged();
    partial void OnAnh_CviecChanging(string value);
    partial void OnAnh_CviecChanged();
    #endregion
		
		public LOAICONGVIEC()
		{
			this._BAIDANGs = new EntitySet<BAIDANG>(new Action<BAIDANG>(this.attach_BAIDANGs), new Action<BAIDANG>(this.detach_BAIDANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(50)")]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this.OnTenloaiChanging(value);
					this.SendPropertyChanging();
					this._Tenloai = value;
					this.SendPropertyChanged("Tenloai");
					this.OnTenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh_Cviec", DbType="NVarChar(50)")]
		public string Anh_Cviec
		{
			get
			{
				return this._Anh_Cviec;
			}
			set
			{
				if ((this._Anh_Cviec != value))
				{
					this.OnAnh_CviecChanging(value);
					this.SendPropertyChanging();
					this._Anh_Cviec = value;
					this.SendPropertyChanged("Anh_Cviec");
					this.OnAnh_CviecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAICONGVIEC_BAIDANG", Storage="_BAIDANGs", ThisKey="Maloai", OtherKey="Maloai")]
		public EntitySet<BAIDANG> BAIDANGs
		{
			get
			{
				return this._BAIDANGs;
			}
			set
			{
				this._BAIDANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAIDANGs(BAIDANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAICONGVIEC = this;
		}
		
		private void detach_BAIDANGs(BAIDANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAICONGVIEC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIUNGTUYEN")]
	public partial class NGUOIUNGTUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNUT;
		
		private string _Hoten;
		
		private string _Diachi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _CV_NUT;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Gioitinh;
		
		private string _Password_NUT;
		
		private EntitySet<HOSOUNGTUYEN> _HOSOUNGTUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNUTChanging(string value);
    partial void OnMaNUTChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCV_NUTChanging(string value);
    partial void OnCV_NUTChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnPassword_NUTChanging(string value);
    partial void OnPassword_NUTChanged();
    #endregion
		
		public NGUOIUNGTUYEN()
		{
			this._HOSOUNGTUYENs = new EntitySet<HOSOUNGTUYEN>(new Action<HOSOUNGTUYEN>(this.attach_HOSOUNGTUYENs), new Action<HOSOUNGTUYEN>(this.detach_HOSOUNGTUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNUT", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNUT
		{
			get
			{
				return this._MaNUT;
			}
			set
			{
				if ((this._MaNUT != value))
				{
					this.OnMaNUTChanging(value);
					this.SendPropertyChanging();
					this._MaNUT = value;
					this.SendPropertyChanged("MaNUT");
					this.OnMaNUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CV_NUT", DbType="NVarChar(500)")]
		public string CV_NUT
		{
			get
			{
				return this._CV_NUT;
			}
			set
			{
				if ((this._CV_NUT != value))
				{
					this.OnCV_NUTChanging(value);
					this.SendPropertyChanging();
					this._CV_NUT = value;
					this.SendPropertyChanged("CV_NUT");
					this.OnCV_NUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(10)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_NUT", DbType="NVarChar(100)")]
		public string Password_NUT
		{
			get
			{
				return this._Password_NUT;
			}
			set
			{
				if ((this._Password_NUT != value))
				{
					this.OnPassword_NUTChanging(value);
					this.SendPropertyChanging();
					this._Password_NUT = value;
					this.SendPropertyChanged("Password_NUT");
					this.OnPassword_NUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIUNGTUYEN_HOSOUNGTUYEN", Storage="_HOSOUNGTUYENs", ThisKey="MaNUT", OtherKey="MaNUT")]
		public EntitySet<HOSOUNGTUYEN> HOSOUNGTUYENs
		{
			get
			{
				return this._HOSOUNGTUYENs;
			}
			set
			{
				this._HOSOUNGTUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOSOUNGTUYENs(HOSOUNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIUNGTUYEN = this;
		}
		
		private void detach_HOSOUNGTUYENs(HOSOUNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIUNGTUYEN = null;
		}
	}
	
	public partial class XuatBDtheoDnResult
	{
		
		private string _TenBD;
		
		private string _Tenloai;
		
		private string _Mota;
		
		private string _Phucloi;
		
		private string _Vitri;
		
		private string _Kinhnghiem;
		
		private string _Dotuoilamviec;
		
		private string _Mucluong;
		
		private System.Nullable<System.DateTime> _Ngaydangbai;
		
		private string _Yeucau;
		
		private string _Trangthai_BD;
		
		public XuatBDtheoDnResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBD", DbType="NVarChar(50)")]
		public string TenBD
		{
			get
			{
				return this._TenBD;
			}
			set
			{
				if ((this._TenBD != value))
				{
					this._TenBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(50)")]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this._Tenloai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(1000)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this._Mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phucloi", DbType="NVarChar(1000)")]
		public string Phucloi
		{
			get
			{
				return this._Phucloi;
			}
			set
			{
				if ((this._Phucloi != value))
				{
					this._Phucloi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri", DbType="NVarChar(1000)")]
		public string Vitri
		{
			get
			{
				return this._Vitri;
			}
			set
			{
				if ((this._Vitri != value))
				{
					this._Vitri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kinhnghiem", DbType="NVarChar(1000)")]
		public string Kinhnghiem
		{
			get
			{
				return this._Kinhnghiem;
			}
			set
			{
				if ((this._Kinhnghiem != value))
				{
					this._Kinhnghiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dotuoilamviec", DbType="NVarChar(100)")]
		public string Dotuoilamviec
		{
			get
			{
				return this._Dotuoilamviec;
			}
			set
			{
				if ((this._Dotuoilamviec != value))
				{
					this._Dotuoilamviec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mucluong", DbType="NVarChar(1000)")]
		public string Mucluong
		{
			get
			{
				return this._Mucluong;
			}
			set
			{
				if ((this._Mucluong != value))
				{
					this._Mucluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangbai", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydangbai
		{
			get
			{
				return this._Ngaydangbai;
			}
			set
			{
				if ((this._Ngaydangbai != value))
				{
					this._Ngaydangbai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yeucau", DbType="NVarChar(1000)")]
		public string Yeucau
		{
			get
			{
				return this._Yeucau;
			}
			set
			{
				if ((this._Yeucau != value))
				{
					this._Yeucau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai_BD", DbType="NVarChar(50)")]
		public string Trangthai_BD
		{
			get
			{
				return this._Trangthai_BD;
			}
			set
			{
				if ((this._Trangthai_BD != value))
				{
					this._Trangthai_BD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
